// <auto-generated />
using System;
using ECommerce.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.EntityFramework.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ECommerce.Data.Models.Columns", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedByColumnsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedColumnsId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByColumnsId");

                    b.HasIndex("UpdatedColumnsId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("ECommerce.Data.Models.Columns", b =>
                {
                    b.HasOne("ECommerce.Data.Models.Columns", "CreatedByColumns")
                        .WithMany()
                        .HasForeignKey("CreatedByColumnsId");

                    b.HasOne("ECommerce.Data.Models.Columns", "UpdatedByColumns")
                        .WithMany()
                        .HasForeignKey("UpdatedColumnssId");

                    b.Navigation("CreatedByColumns");

                    b.Navigation("UpdatedByColumns");
                });
#pragma warning restore 612, 618
        }
    }
}
